require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
    - Gemfile

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/MultipleExpectations:
  Enabled: false
