version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ../rails-graphql-bootstrap-postgres:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ../rails-graphql-bootstrap-redis:/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - REDIS_HOST=redis
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - REDIS_HOST=redis
