config:
  dockerfile: .woloxci/Dockerfile
  project_name: rails-graphql-bootstrap

services:
  - postgres

steps:
  analysis:
    - bundle exec rubocop app spec --format simple
    - bundle exec rubycritic --minimum-score 80 --no-browser
  setup_db:
    - bundle exec rails db:create
    - bundle exec rails db:schema:load
  test:
    - bundle exec rspec spec -fd
  security:
    - bundle exec brakeman -q --no-summary
  audit:
    - bundle exec bundle audit check --update --quiet

environment:
  RAILS_ENV: test
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
